services:
  catalogdb:
    image: postgres:16.8-alpine3.20
    # build:
    #     dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basketdb:
    image: postgres:16.8-alpine3.20

  distributedcache:
    image: redis

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/Catalog.API/Dockerfile

  basket.api:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/Basket.API/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:
